### PR TITLE
Create PV plugin for uncertain critical points filters

### PR DESCRIPTION
**Pull request by kmorel**

### CODE REVIEW

**Comment by kmorel** [comment]
@wangzhezhe Here is the code to create a PV plugin for the histogram version of the uncertain critical points algorithm.

This should compile against ParaView 5.12.0. I got around the problem of long tuples by duplicating the code in the VTK MR. (I actually found a secondary issue that had to be fixed anyway.)

Let me know how this works for you.

**Comment by wangzhezhe** [comment]
Sure, thanks so much for the help! Let me try it and let you know if there are issues to run it.

**Comment by wangzhezhe** [comment]
It works on my device, thanks for the help!
If we try to compile the vtkm through ParaView on GPU device, is it possible to set associated compiling parameters? Such as  `-DVTKm_ENABLE_CUDA=ON`.

**Comment by kmorel** [comment]
I think you can just set `VTKm_ENABLE_CUDA`. I also see a `PARAVIEW_USE_CUDA` option, but that might be obsolete. It might help to look at the [paraview spack configuration](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/paraview/package.py) for the [+cuda](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/paraview/package.py#L572) option to see how it configures ParaView. Or you can just build ParaView with spack. I believe it installs the header files needed to build plugins like this.

**Comment by wangzhezhe** [comment]
Sure, thanks a lot for the information, let me try it, could we also use hip based on kokkos when using vtk-m as a plugin of ParaView? or we can just use the cuda backend of the vtk-m.

**Comment by kmorel** [comment]
I don't understand the question. Are you asking if you can turn on hip support to enable cuda (through Kokkos)? That doesn't sound like a great idea.

**Comment by wangzhezhe** [comment]
Sure, good to know that, yeah, we try to compile the plugin with GPU backend. We are considering using Frontier or other local devices with CUDA support. We might try CUDA backend if it is complicated to compile the plugin through kokkos hip backend.

**Pull request merged**
